// config.h  Generated by cmake.

// Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
#cmakedefine HAVE_DIRENT_H

// Define to 1 if you have the <ndir.h> header file, and it defines `DIR'.
#cmakedefine HAVE_NDIR_H

// Define to 1 if you have the <pthread.h> header file.
#cmakedefine HAVE_PTHREAD_H

// Define to 1 if you have the <pwd.h> header file.
#cmakedefine HAVE_PWD_H

// Define to 1 if you have the <sqlite3.h> header file.
#cmakedefine HAVE_SQLITE3_H

// Define to 1 if you have the <sqlite.h> header file.
#cmakedefine HAVE_SQLITE_H

// Define to 1 if you have the <stdlib.h> header file.
#cmakedefine HAVE_STDLIB_H

// Define to 1 if you have the <string.h> header file.
#cmakedefine HAVE_STRING_H

// Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
#cmakedefine HAVE_SYS_DIR_H

// Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
#cmakedefine HAVE_SYS_NDIR_H

// Define to 1 if you have the <sys/stat.h> header file.
#cmakedefine HAVE_SYS_STAT_H

// Define to 1 if you have the <tinyxml.h> header file.
#cmakedefine HAVE_TINYXML_H

// Define to 1 if you have the <unistd.h> header file.
#cmakedefine HAVE_UNISTD_H

// Define to 1 if you have the <X11/extensions/Xevie.h> header file.
#cmakedefine HAVE_X11_EXTENSIONS_XEVIE_H

// Define to 1 if you have the <X11/keysymdef.h> header file.
#cmakedefine HAVE_X11_KEYSYMDEF_H

// Define to 1 if you have the <X11/Xlib.h> header file.
#cmakedefine HAVE_X11_XLIB_H

// Define to 1 if you have the <X11/Xproto.h> header file.
#cmakedefine HAVE_X11_XPROTO_H

// Define to 1 if you have the <X11/Xutil.h> header file.
#cmakedefine HAVE_X11_XUTIL_H

// Define to 1 if you have the <X11/X.h> header file.
#cmakedefine HAVE_X11_X_H

// Name of package
#cmakedefine PACKAGE "@PACKAGE@"

// Define to the address where bug reports for this package should be sent.
#cmakedefine PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"

// Define to the full name and version of this package.
#cmakedefine PACKAGE_STRING "@PACKAGE_STRING@"

// Define to 1 if you have the ANSI C header files.
#cmakedefine STDC_HEADERS

// Define to 1 to use STL string in TinyXML
#cmakedefine TIXML_USE_STL

// Define to 1 if you want to use SQLite
#cmakedefine USE_SQLITE

// Version number of package
#cmakedefine VERSION "@VERSION@"
