baseURL = "http://example.org/"
languageCode = "en-us"
title = "presage"
theme = "ananke"
Paginate = 6

[params]
  favicon = "presage.ico"
  description = "the intelligent predictive text entry system"
#  featured_image = "/images/presage-hero-image.jpg"
#  featured_image = ""
  background_color_class = 'presage-bg-gray'
  custom_css = ["css/presage.css"]
#  linkedin = "https://www.linkedin.com/in/matteo-vescovi-2410076/"
  author = "Matteo Vescovi"
  author_website = "http://multithread.org"
