baseURL = "http://example.org/"
languageCode = "en-us"
title = "presage"
theme = "ananke"
Paginate = 6

[params]
  favicon = "presage.ico"
  description = "the intelligent predictive text entry system"
#  featured_image = "/images/presage-hero-image.jpg"
  background_color_class = 'presage-bg-gray'
  custom_css = ["css/presage.css"]
